---

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu2404
    image: jrei/systemd-ubuntu:24.04
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    pull: true
    systemd: always

provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
  inventory:
    host_vars:
      ssherlock-host:
        hostname: ssherlock-host
    group_vars:
      all:

verifier:
  name: ansible
