---

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu2404
    image: jrei/systemd-ubuntu:24.04
    privileged: true
    pre_build_image: true
    systemd: always

provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
  inventory:
    host_vars:
      ssherlock-host:
        hostname: ssherlock-host
    group_vars:
      all:
        ansible_user: root

verifier:
  name: ansible
