---

dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    requirements-file: collections.yml
driver:
  name: docker
platforms:
  - name: ubuntu2404
    image: jrei/systemd-ubuntu:24.04
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /usr/sbin/init
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
  inventory:
    host_vars:
      ubuntu-host:
        hostname: ubuntu-host
    group_vars:
      all:
        ansible_user: root
        interactive_account:
          username: alice
          comment: Alice
          home_dir: /home/alice
          pubkeys:
            - "{{ lookup('file', '../../keys/public.key') }}"
        service_account:
          username: ansible
          comment: Service account
          home_dir: /var/lib/ansible
          pubkeys:
            - "{{ lookup('file', '../../keys/public.key') }}"
verifier:
  name: ansible
