---
# yamllint disable

- name: MAIN | Create SSHerlock group
  ansible.builtin.group:
    name: "{{ ssherlock_user }}"
  notify:
    - restart-ssherlock-runners
    - restart-ssherlock-server

- name: MAIN | Create SSHerlock user
  ansible.builtin.user:
    name: "{{ ssherlock_user }}"
    comment: Django SSHerlock service account
    group: "{{ ssherlock_user }}"
    create_home: false
    system: true
  notify:
    - restart-ssherlock-runners
    - restart-ssherlock-server

- name: MAIN | Copy SSHerlock to target server
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ssherlock_app_path }}"
    owner: "{{ ssherlock_user }}"
    group: "{{ ssherlock_user }}"
    mode: "0644"
    backup: true
  loop:
    - ssherlock/
    - requirements.txt
  notify:
    - migrate-ssherlock-database
    - restart-ssherlock-runners
    - restart-ssherlock-server

- name: MAIN | Install Python dependencies
  ansible.builtin.pip:
    requirements: "{{ ssherlock_app_path }}/requirements.txt"
    virtualenv: "{{ ssherlock_venv_path }}"
    virtualenv_python: python3
  notify:
    - restart-ssherlock-runners
    - restart-ssherlock-server

- name: MAIN | Install Apt dependencies
  ansible.builtin.apt:
    name: nginx=1.24.0-2ubuntu7.1
    autoclean: true
    autoremove: true
    clean: true
    update_cache: true
  notify:
    - restart-ssherlock-runners
    - restart-ssherlock-server

- name: MAIN | Create symlink to application directory
  ansible.builtin.file:
    src: "{{ ssherlock_app_path }}"
    dest: /ssherlock
    state: link

- name: MAIN | Deploy templates
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: /{{ item }}
    mode: "0640"
    owner: root
    group: root
  loop:
    - etc/nginx/nginx.conf
    - etc/systemd/system/gunicorn.service
    - etc/systemd/system/gunicorn.socket
    - etc/systemd/system/ssherlock_runner@.service
    - etc/systemd/system/ssherlock_runners.target
  notify:
    - restart-ssherlock-runners
    - restart-ssherlock-server
