---

- name: MAIN | Create SSHerlock group
  ansible.builtin.group:
    name: ssherlock
  notify:
    - restart-ssherlock-runners
    - restart-ssherlock-server

- name: MAIN | Create SSHerlock user
  ansible.builtin.user:
    name: ssherlock
    comment: Django SSHerlock service account
    group: ssherlock
    create_home: false
    system: true
  notify:
    - restart-ssherlock-runners
    - restart-ssherlock-server

- name: MAIN | Install Python dependencies
  ansible.builtin.pip:
    requirements: "{{ app_path }}/requirements.txt"
    virtualenv: "{{ venv_path }}"
    virtualenv_python: python3
  notify:
    - restart-ssherlock-runners
    - restart-ssherlock-server

- name: MAIN | Install Apt dependencies
  ansible.builtin.apt:
    name:
      - nginx==1.8.0
    autoclean: true
    autoremove: true
    clean: true
    update_cache: true
  notify:
    - restart-ssherlock-runners
    - restart-ssherlock-server

- name: MAIN | Copy SSHerlock code to target server
  ansible.builtin.copy:
    src: ssherlock
    dest: {{ app_path }}
    owner: ssherlock
    group: ssherlock
    mode: "0644"
    backup: true
  register: ssherlock_code
  notify:
    - restart-ssherlock-runners
    - restart-ssherlock-server

- name: MAIN | Create symlink to application directory
  ansible.builtin.file:
    src: {{ app_path }}
    dest: /ssherlock
    state: link

- name: MAIN | Deploy templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0640"
    owner: root
    group: root
  loop:
    - src: etc/systemd/system/gunicorn.service.j2
      dest: /etc/systemd/system/gunicorn.service

    - src: etc/systemd/system/ssherlock_runner.service.j2
      dest: /etc/systemd/system/ssherlock_runner@.service

    - src: etc/systemd/system/ssherlock_runners.target.j2
      dest: /etc/systemd/system/ssherlock_runners.target
  notify:
    - restart-ssherlock-runners
    - restart-ssherlock-server

- name: MAIN | Run database migrations
  ansible.builtin.shell:
    cmd: |
      "{{ app_path }}/venv/bin/python ssherlock/ssherlock_server/manage.py makemigrations ssherlock_server"
      "{{ app_path }}/venv/bin/python ssherlock/ssherlock_server/manage.py migrate"
    chdir: "{{ app_path }}"
  when: ssherlock_code.changed
  notify:
    - restart-ssherlock-runners
    - restart-ssherlock-server
