---

- name: HANDLERS | SSHerlock runners restarted
  systemd:
    name: ssherlock_runners.target
    state: restarted
    enabled: true
    masked: false
    daemon_reload: true
  listen: restart-ssherlock-runners

- name: HANDLERS | SSHerlock Server restarted (gunicorn)
  systemd:
    name: gunicorn.socket
    state: restarted
    enabled: true
    masked: false
    daemon_reload: true
  listen: restart-ssherlock-server

- name: HANDLERS | SSHerlock Server restarted (nginx)
  systemd:
    name: nginx.service
    state: restarted
    enabled: true
    masked: false
    daemon_reload: true
  listen: restart-ssherlock-server
