---
# yamllint disable

- name: HANDLERS | SSHerlock runners restarted
  ansible.builtin.systemd:
    name: ssherlock_runners.target
    state: restarted
    enabled: true
    masked: false
    daemon_reload: true
  listen: restart-ssherlock-runners

- name: HANDLERS | SSHerlock Server restarted (gunicorn)
  ansible.builtin.systemd:
    name: gunicorn.socket
    state: restarted
    enabled: true
    masked: false
    daemon_reload: true
  listen: restart-ssherlock-server

- name: HANDLERS | SSHerlock Server restarted (nginx)
  ansible.builtin.systemd:
    name: nginx.service
    state: restarted
    enabled: true
    masked: false
    daemon_reload: true
  listen: restart-ssherlock-server

- name: HANDLERS | SSHerlock database migrated
  ansible.builtin.shell:
    cmd: |
      "{{ ssherlock_venv_path }}/bin/python manage.py makemigrations ssherlock_server"
      "{{ ssherlock_venv_path }}/bin/python manage.py migrate"
    chdir: "{{ ssherlock_app_path }}"
  listen: migrate-ssherlock-database
