---
# yamllint disable

- name: HANDLERS | Timesyncd restarted
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted
    enabled: true
    masked: false
  when: not ubuntu_server_running_in_molecule
  listen: restart-systemd-timesyncd

- name: HANDLERS | Unattended-upgrades restarted
  ansible.builtin.systemd:
    name: unattended-upgrades
    state: restarted
    enabled: true
    masked: false
  when: not ubuntu_server_running_in_molecule
  listen: restart-unattended-upgrades

- name: HANDLERS | SSHD restarted
  ansible.builtin.systemd:
    name: sshd
    state: restarted
  when: not ubuntu_server_running_in_molecule
  listen: restart-sshd
