---

# ansible-playbook pb-deploy-app.yml -v -kK -e "user=akelley"

- name: Deploy SSHerlock Server and Runner
  hosts: watson
  gather_facts: true
  become: true
  become_method: ansible.builtin.sudo
  remote_user: "{{ user | default('ansible') }}"
  vars:
    ansible_user: "{{ user | default('ansible') }}"
  roles:
    - role: ssherlock
      tags: ssherlock_role
