---

- name: HOST | Edit hosts.conf
  ansible.builtin.copy:
    dest: /etc/hosts
    mode: "0644"
    content: |
      # Static table lookup for hostnames.
      # See hosts(5) for details.
      127.0.0.1 localhost
      {% if domain is defined and domain !="" %}
      127.0.1.1 {{ hostname }}.{{ domain }} {{ hostname }} localhost
      {% else %}
      127.0.1.1 {{ hostname }} localhost
      {% endif %}
      ::1     localhost ip6-localhost ip6-loopback
      fe00::0 ip6-localnet
      ff00::0 ip6-mcastprefix
      ff02::1 ip6-allnodes
      ff02::2 ip6-allrouters

- name: HOST | Forcibly set DNS in resolv.conf
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    line: nameserver {{ dns_server }}
    insertbefore: BOF
  when: force_dns
