---

name: Ansible

on:  # yamllint disable-line
  push:
    paths:
      - 'ansible/**'
      - '.github/**'

jobs:

  ansible_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          args: ""
          setup_python: "true"
          working_directory: ./ansible/
          requirements_file: ""

  molecule_ubuntu_server_role:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: converge
          molecule_working_dir: ./ansible/roles/ubuntu_server

  molecule_ssherlock_role:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: converge
          molecule_working_dir: ./ansible/roles/ssherlock
