---

name: Lint and test Ansible

on:
  push:
    paths:
      - 'ansible/**'

jobs:

  ansible_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          args: ""
          setup_python: "true"
          working_directory: "${GITHUB_REPOSITORY}/ansible/"
          requirements_file: ""

  molecule_ubuntu_server_role:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: converge
          molecule_working_dir: "${GITHUB_REPOSITORY}/ansible/roles/ubuntu_server"

  molecule_ssherlock_role:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: converge
          molecule_working_dir: "${GITHUB_REPOSITORY}/ansible/roles/ssherlock"
