---

name: Ansible

on:  # yamllint disable-line
  push:
    paths:
      - 'ansible/**'
      - '.github/**'

jobs:

  ansible_lint:
    name: Lint Ansible
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          args: --skip-list=no-handler,no-changed-when,command-instead-of-module,var-naming[no-role-prefix]
          setup_python: true
          working_directory: ./ansible/
          requirements_file: ./ansible/roles/ubuntu_server/collections.yml

  molecule_ubuntu_server:
    name: Molecule (Ubuntu Server role)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"

      - name: Run molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
          molecule_working_dir: "${{ github.repository }}/ansible/roles/ubuntu_server"

  molecule_ssherlock:
    name: Molecule (SSHerlock role)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"

      - name: Copy SSHerlock directory into Ansible role directory
        run: |
          cp -rav "${{ github.repository }}/ssherlock" "${{ github.repository }}/ansible/roles/ssherlock/files/"
          cp -rav "${{ github.repository }}/requirements.txt" "${{ github.repository }}/ansible/roles/ssherlock/files/"

      - name: Run molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
          molecule_working_dir: "${{ github.repository }}/ansible/roles/ssherlock"
