---

name: Ansible

on:  # yamllint disable-line
  push:
    paths:
      - 'ansible/**'
      - '.github/**'

jobs:

  ansible_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          args: ""
          setup_python: "true"
          working_directory: ./ansible/
          requirements_file: ""

  molecule_ubuntu_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"

      - name: Run molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
          molecule_working_dir: "${{ github.repository }}/ansible/roles/ubuntu_server"

  molecule_ssherlock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"

      - name: Copy main SSHerlock directory into the Ansible role
        run: cp -rav "${{ github.repository }}/ssherlock" "${{ github.repository }}/ansible/roles/ssherlock/files/"

      - name: Run molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
          molecule_working_dir: "${{ github.repository }}/ansible/roles/ssherlock"
